# RT profiles to apply for CI, unit tests, benchmarks, examples, etc
# These are not meant for real world deployment!!

# --- TEST PROFILES ---
# loaded only by unit tests, benchmarks, etc

benchmark_gasp_collision_detection: # if on robot PC use [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
  affinity: [0, 2, 4, 6, 8, 10]

test_collision_detection_0:
  affinity: []

test_collision_detection_1:
  affinity: [2]

test_collision_detection_2:
  affinity: [2, 4]

test_collision_detection_3:
  affinity: [2, 4, 6]

test_collision_detection_4:
  affinity: [2, 4, 6, 8]

test_collision_detection_5:
  affinity: [2, 4, 6, 8, 10]

test_staubli_mpc:
  affinity: [4, 5, 6, 7]

test_nlpfree_mpc:
  affinity: [4, 5, 6]

test_profile_manager:
  affinity: [3, 4]
  policy: SCHED_FIFO
  priority: 89

test_profile_manager_utils:
  affinity: [1, 2, 3, 4, 5, 6, 7, 8]

test_transformer_state_estimator:
  affinity: [6]

# --- DEPLOYMENT PROFILES ---
# loaded by deployment code reached by unit tests etc
# so need to be defined also in CI

collision_detection_robot_interface: null
collision_detection_control_wrapper: null
open_loop_ruckig: null
arena_native_ros: null
arena_tactics: null
trajectory_estimator: null
musashi_interface_logger: null
multistep_action_process: null
