
capture:
  worker_queue_length: 2
  camera_buffer_length: 2
  use_variable_response_time: true

person_detector:
  device_index: 0
  conf_threshold: 0.3
  nms_threshold: 0.65
  sampling: 1
  topK: 1
  bbox_inflation: [0.5,0.2]
  history_difference: 100 # max sequence ID difference
  latest_weight: 0.9
  batch_size: 4

extractor:
  device_index: 0
  sampling: 2
  outdated_diff: 16
  workers_count: 1
  apply_rotation_correction: True
  history_difference: 30 # max sequence ID difference
  latest_weight: 0.9
  min_keypoint_confidence: 0.3
  undistort_keypoints: false
  rt_profile: player_pose_extractor

triangulation:
  covariance_model: metric
  geometric_error_threshold: 10.
  radius_error_threshold: 0.15
  observation_variance: 0.04
  nonlinear_refinement:
    use: true
    tol_position: 1e-10
    tol_reprojection_error: 1e-8
    max_iterations: 100
