#!/usr/bin/env python3
# pylint: disable = too-many-locals, unused-variable, too-many-branches, too-many-statements
# Confidential, Copyright 2024, Sony AI, All rights reserved.
"""
Test for EVS synchronization using an LED panel.
"""
import os
import argparse
from pathlib import Path

import math
import heapq
import numpy as np
import cv2
import matplotlib.pyplot as plt
from skimage.measure import regionprops
from evs.utilities.event_readers import FixedDurationEventRawReader
from triangulation import python_module as triangulation
from calibration import python_module as calibration


def events_to_frame(events, width, height):
    """
    Generates event frames.

    Returns event frames with values corresonding to scaled number of events.
    """
    event_frame = np.zeros((3, height, width), np.uint8)
    x_events = events[:, 1].astype(int)
    y_events = events[:, 2].astype(int)
    pols = events[:, 3]
    # Polarity should be +1 / -1

    for i, x_event in enumerate(x_events):
        if pols[i] == 1:
            event_frame[0, y_events[i], x_event] += 1
        else:
            event_frame[1, y_events[i], x_event] += 1

    min_val = event_frame.min()
    max_val = event_frame.max()
    event_frame = 255 * ((event_frame - min_val) / (max_val - min_val))
    return event_frame


def parse_args():
    """
    Parses the input arguments
    @return: Parsed argument struct
    """
    parser = argparse.ArgumentParser(
        description='Reads external triggers from evs recording and stores them in a ".txt" file.'
    )
    parser.add_argument(
        "raw_files",
        type=str,
        help="Path to raw recordings.",
    )
    parser.add_argument(
        "output_path",
        type=str,
        help="Path to output images.",
    )
    parser.add_argument(
        "dt",
        type=int,
        default=1000,
        help="Accumulation time [in us] (default 1khz: %(default)s).",
    )
    parser.add_argument(
        "num_leds",
        type=int,
        default=60,
        help="Threshold, how many sequentially detected LEDs [#] (default: %(default)s).",
    )
    parser.add_argument(
        "config",
        type=str,
        help="Camera calibration setup(e.g. zrh01).",
    )

    return parser.parse_args()


def extract_led_array(
    raw_file: str,
    d_t: int,
    start_t: float,
    end_t: float,
    cam_idx: int,
    thresh_leds: int,
    output_path: str,
):
    """
    Reads external raw file, generates event histograms, computes center of mass and detects reoccuring LEDs
    @return: last timestamp that was used, array with center of mass, array of timestamps
    """
    # Check if raw file exists
    assert Path(raw_file).exists()

    # Check if raw file is .raw
    assert Path(raw_file).suffix == ".raw"

    number_leds = 100
    threshold_background = 100
    event_iterator = FixedDurationEventRawReader(raw_file, d_t, start_t)
    leds_array = [np.array((0, 0))] * number_leds
    ts_array = [0] * number_leds
    last_ts = 0

    led_found = False
    found_one = 0
    # Find repeating LEDs
    for idx, event_window in enumerate(event_iterator):
        if event_window[:, 0].size > 0:
            if (event_window[:, 0][-1] > start_t) and (event_window[:, 0][-1] < end_t):
                event_histogram = events_to_frame(event_window, width=1280, height=720)
                img_path = output_path + "/" + str(cam_idx) + "_" + str(idx) + ".jpg"
                new_img = np.zeros((720, 1280, 3))
                new_img[:, :, 0] = event_histogram[0]
                new_img[:, :, 2] = event_histogram[1]
                labeled_foreground = (new_img[:, :, 0] > threshold_background).astype(int)
                properties = regionprops(labeled_foreground, new_img[:, :, 0])
                if len(properties) == 0:
                    continue
                center_of_mass = properties[0].centroid
                if (
                    math.dist(leds_array[idx % number_leds], center_of_mass) < 2
                    and leds_array[idx % number_leds][0] != 0
                ):  # experimental threhold of 2px
                    found_one += 1
                    if found_one == thresh_leds:
                        led_found = True
                else:
                    found_one = 0
                leds_array[idx % number_leds] = center_of_mass
                last_ts = event_window[:, 0][-1]
                ts_array[idx % number_leds] = event_window[:, 0][-1]
                if (led_found is True) and (end_t == float("inf")):
                    cv2.imwrite(img_path, new_img)
                    return event_window[:, 0][-1], leds_array, ts_array
            elif event_window[:, 0][-1] >= end_t:
                # Just for visualization
                cv2.imwrite(img_path, new_img)
                color = (0, 255, 0)
                marker_type = cv2.MARKER_CROSS
                marker_size = 5
                thickness = 1
                img = cv2.imread(img_path)
                cv2.drawMarker(
                    img,
                    (
                        int(leds_array[(idx - 1) % 100][1]),
                        int(leds_array[(idx - 1) % 100][0]),
                    ),
                    color,
                    marker_type,
                    marker_size,
                    thickness,
                )
                cv2.imwrite(img_path, img)
                return last_ts, leds_array, ts_array
    return last_ts, leds_array, ts_array


def run_sync_check(raw_file: str, output_path: str, d_t: int, thresh_leds: int, config: str):
    """
    Reads external triggers from evs raw recording and stores them in a \".txt\" file."
    """

    exists = os.path.exists(output_path)
    if not exists:
        # Create a new directory because it does not exist
        os.makedirs(output_path)

    # Extract triggers
    start_times = []
    led_arrays = []
    cam_points = []
    cam_idx = 0
    for file in os.listdir(raw_file):
        print(file)
        assert Path(os.path.join(raw_file, file)).exists()
        # Event iteration creates tmp_index files, ignore them
        if Path(os.path.join(raw_file, file)).suffix == ".tmp_index":
            continue
        # Find repeaing LEDs
        start_t, led_array, ts_array = extract_led_array(
            os.path.join(raw_file, file),
            d_t,
            0.0,
            float("inf"),
            cam_idx,
            thresh_leds,
            output_path,
        )
        cam_idx += 1
        # Time when repeating LEDs are detected for different cameras
        start_times.append(start_t)
    # Camera that took the longest time to detect LEDs, store timestamp
    max_time = max(start_times)
    # Reiterated through events up until this longest timestamp
    cam_idx = 0
    last_times = []
    cameras = []
    for file in os.listdir(raw_file):
        assert Path(os.path.join(raw_file, file)).exists()
        if Path(os.path.join(raw_file, file)).suffix == ".tmp_index":
            continue
        last_t, led_array, ts_array = extract_led_array(
            os.path.join(raw_file, file),
            d_t,
            0.0,
            max_time,
            cam_idx,
            thresh_leds,
            output_path,
        )
        split_filename = os.path.splitext(str(file))
        cameras.append(split_filename[0])

        led_arrays.append(led_array)
        cam_idx += 1
        last_times.append(last_t)
        # Get index of when the last event histogram was created
        # These indices should be identical for all cameras if they are synchronized
        idx_end = np.where(ts_array == last_t)
        # Some logig for obtaining the last #n LEDs (center of mass in image space)
        if idx_end[0][0] - thresh_leds < 0:
            cam_points.append(led_array[idx_end[0][0] - thresh_leds :] + led_array[: idx_end[0][0]])
        else:
            cam_points.append(led_array[idx_end[0][0] - thresh_leds : idx_end[0][0]])

    abs_path = Path(__file__).parent.parent.parent.absolute()
    calib_path = os.path.join(abs_path, "calibration/parameters/camera_calibration/" + config + ".yaml")
    calib_params = calibration.CameraCalibrationParameters()
    calib_params.initialize(str(calib_path))

    triangultor_params = triangulation.TriangulationParameters()
    triangultor_params.geometric_error_threshold = 0.75
    triangultor_params.radius_error_threshold = 100000.15
    triangultor_params.use_nonlinear_refinement = False
    triangultor_params.tol_position = 1e-10
    triangultor_params.tol_reprojection_error = 1e-8
    triangultor_params.max_iterations = 1

    triangulator = triangulation.Triangulation(triangultor_params, calib_params)
    triangulator.set_cameras(cameras)
    points_3d = []
    pos_x = []
    pos_y = []
    pos_z = []
    do_triang = True
    for i in range(thresh_leds):
        points_2d = []
        idx = 0
        for file in os.listdir(raw_file):
            assert Path(os.path.join(raw_file, file)).exists()
            if Path(os.path.join(raw_file, file)).suffix == ".tmp_index":
                do_triang = False
                continue
            do_triang = True
            # Points need to be flipped in x and y
            if cam_points[idx][i][0] != 0:
                points_2d.append([np.flip(np.asarray(cam_points[idx][i]))])
            else:
                points_2d.append([])
            idx += 1
        if do_triang:
            result_3d = triangulator.triangulate_points(points_2d)
            # Pos_x/y/z are used for visualization later
            if len(result_3d) > 0:
                points_3d.append(result_3d[0].position)
                pos_x.append(result_3d[0].position[0])
                pos_y.append(result_3d[0].position[1])
                pos_z.append(result_3d[0].position[2])
            else:
                points_3d.append([])

    idx_start = []
    jump_pos = []
    # Get distanced between LEDs in 2D, for all cameras
    for i, camera in enumerate(led_arrays):
        dist = []
        for j, led in enumerate(led_arrays[i]):
            if j + 1 < len(led_arrays[i]):
                dist.append(np.linalg.norm(np.asarray(camera[j + 1]) - np.asarray(camera[j])))
            else:
                dist.append(np.linalg.norm(np.asarray(camera[0]) - np.asarray(camera[j])))
        # Get 10 largest distances (since big jump after every 10th LED on the panel)
        largest = [dist.index(i) for i in heapq.nlargest(10, dist)]
        # dist_max = dist.index(max(dist))
        idx_start.append(largest)
        jump_leds = 0
        mod_leds = np.asarray(idx_start[i]) % 10
        for k, mod_led in enumerate(mod_leds):
            jump_leds = mod_leds.tolist().count(mod_led)
            # Find if the large jump happens consistently after 10 LEDS (mod 10) at least in 5 cases
            if jump_leds > 5:
                jump_pos.append(mod_led)
                break
            if jump_leds == 0:
                raise SystemExit("FAIL. No common LEDs detected between cameras.")
    print(f"Jump happens at modulo: {jump_pos} Success Test 1: {jump_pos[1:] == jump_pos[:-1]}")
    # Find large jumps that happen for all cameras at the same time
    set_same = set(idx_start[0])
    idx = 0
    for set_val in idx_start[1:]:
        set_same.intersection_update(set_val)
        if len(set_same) == 0:
            set_same = set(idx_start[idx])
        idx += 1
    if len(set_same) == 0:
        raise SystemExit("Test failed. No LEDs in common")
    points_2d = []
    pos_x2 = []
    pos_y2 = []
    pos_z2 = []
    last_pos = np.zeros(3)
    # For the first set intersection of these large distances, get center of mass in pixel space
    for i, led in enumerate(led_arrays):
        points_2d.append([led[list(set_same)[0]]])
    # Triangulate with all different camera combinations
    for i, led in enumerate(led_arrays):
        triang_point = []
        for j, val in enumerate(led_arrays):
            if i + 1 == len(led_arrays):
                triang_point = [np.flip(points_2d[0]), [], [], np.flip(points_2d[-1])]
            elif j in (i, i + 1):
                triang_point.append(np.flip(points_2d[j]))
            else:
                triang_point.append([])
        same_led_3d = triangulator.triangulate_points(triang_point)
        if len(same_led_3d) > 0:
            pos_x2.append(same_led_3d[0].position[0])
            pos_y2.append(same_led_3d[0].position[1])
            pos_z2.append(same_led_3d[0].position[2])
            if i > 0:
                dist_points_3d = np.linalg.norm(last_pos - np.asarray(same_led_3d[0].position))
                if dist_points_3d < 0.01:
                    print(f"Success Test 2: True. Distance between points in m: {dist_points_3d}")
                else:
                    raise SystemExit("FAIL. Distance between points too large. Evaluate also calibration")
            last_pos = np.asarray(same_led_3d[0].position)
        else:
            raise SystemExit("FAIL. No common LEDs detected between cameras.")

    axis = plt.figure().add_subplot(projection="3d")
    axis.scatter(pos_x, pos_y, pos_z)
    axis.set_aspect("equal")
    axis.scatter(pos_x2, pos_y2, pos_z2, color="red", marker="x", s=8.0)
    plt.savefig(output_path + "/LEDs_3d_" + config + ".jpg")


if __name__ == "__main__":
    args = parse_args()

    run_sync_check(args.raw_files, args.output_path, args.dt, args.num_leds, args.config)
