#!/bin/bash
# Confidential, Copyright 2024, Sony AI, All rights reserved.
set -ex

echo "What is the EVS recording path?"
read evs_path

echo "Which EVS is master?"
read evs_master

echo "What is the APS recording path?"
read aps_path

echo "What should be the output folder path?"
read output_path

##### Extract trigger timestamps from EVS master
evs_trigger_to_txt "$evs_path/evs/$evs_master.raw" "$evs_path/trigger.txt"

mkdir $output_path
mkdir "$output_path/evs"
FILES_EVS="$evs_path/evs/*.raw"

#####  Run reconstruction in different processes
# for filename in $FILES_EVS
# do
#     echo "file $filename"
#     save_folder=${filename%.raw}
#     evs_run_reconstruction -c "ext/e2vid/pretrained/E2VID_lightweight.pth.tar" -i "$filename" --window_size "150000" --trigger_file "$evs_path/trigger.txt" --auto_hdr --output_folder "$save_folder"
# done
# ##### Wait until reconstruction is finished
# wait

#### Copy to correct folder structure
cp -r "$aps_path/aps" "$output_path/aps"
for filename in $FILES_EVS
do
    save_folder=${filename%.raw}
    evs_name=${save_folder#*evs}
    echo "evs name ${evs_name}"
    rm "$save_folder/reconstruction/timestamps.txt"
    cp -r "$save_folder/reconstruction" "$output_path/evs${evs_name}"
done

##### Run calibr
calibration_run_kalibr "$output_path"
