<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>evs_ball_cpp</name>
  <version>1.0.0</version>
  <description>Package to detect balls from evs cameras with YOLO network.</description>
  <maintainer email="raphaela.kreiser@sony.com">SonyAI-Zurich</maintainer>
  <license>Confidential, Copyright 2025, Sony AI, All rights reserved.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>custom_yaml</depend>
  <depend>custom_interfaces</depend>
  <depend>base_parameters</depend>
  <depend>rclcpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
