#!/usr/bin/env python3
"""Calibration files merging helper script"""
# SPDX-License-Identifier: MIT

import os
import click

import ace_yaml as yaml
import numpy as np
from ament_index_python.packages import get_package_share_directory
from calibration import python_module as calibration


@click.command()
@click.option(
    "--first",
    help="First calibration file",
    required=True,
    type=str,
)
@click.option(
    "--second",
    help="Second calibration file",
    required=True,
    type=str,
)
@click.option(
    "--camera",
    help="Shared camera name",
    required=True,
    type=str,
)
@click.option(
    "--config",
    help="Config name to save",
    required=True,
    type=str,
)
def main(first, second, camera, config):
    """Helper script to merge two calibration files into a single one.
    This script requires to have `camera` shared between both files in order to perform correct transformations.
    `first` Calibration is assumed to be the super set calibration, thus all transformations will occur in its space.
    There is no assumption here about T_WO matrix, but if it exists, then the one in `first` calibration will be used.
    As a result of merge, the merged calibration file will be placed under
    `calibration/parameters/camera_calibration/[config].yaml`.
    Usage example:
    calibration_merge_calibrations --first config_a.yaml --second config_b.yaml --camera aps_123456 --config tyo01
    """
    with open(first, encoding="utf8") as yaml_file:
        calib_1 = yaml.load(yaml_file)
    with open(second, encoding="utf8") as yaml_file:
        calib_2 = yaml.load(yaml_file)

    assert camera in calib_1
    assert camera in calib_2

    # populate cameras in calib_2, transform them to calib_1, and merge them to calib_1
    T_cam_first = np.linalg.inv(calib_2[camera]["T_CW"])  # pylint: disable=invalid-name
    T_cam_second = calib_1[camera]["T_CW"]  # pylint: disable=invalid-name
    for cam in calib_2:
        if cam == camera or cam in calib_1:
            continue
        info = calib_2[cam]
        info["T_CW"] = ((info["T_CW"] @ T_cam_first) @ T_cam_second).tolist()
        calib_1[cam] = info

    with open(
        os.path.join(get_package_share_directory("calibration"), "parameters", "camera_calibration", config + ".yaml"),
        mode="w",
        encoding="utf8",
    ) as yaml_file:
        yaml.dump(calib_1, yaml_file)
    calib_params = calibration.CameraCalibrationParameters()
    result_path = os.path.join(
        get_package_share_directory("calibration"), "parameters", "camera_calibration", config + ".yaml"
    )
    print(f"Writing result to {result_path}")
    calib_params.initialize(result_path)
    calib_params.write_parameters_to_file()


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
