#!/usr/bin/env python3
# Confidential, Copyright 2024, Sony AI, All rights reserved.
"""
Set the origin of a calibrated camera system.

This script loads an ACE camera calibration file and an APS camera.
In the APS camera, the script tries to detect an Aprilgrid and compute its pose.
Upon exit of the script, the Aprilgrid pose is taken as origin and written
to the camera calibration file.
"""
# pylint: disable = line-too-long, import-error, no-name-in-module, no-member

import argparse
import sys
import time

import cv2
import numpy as np
import ace_yaml as yaml

# ace
from aps import python_module as aps
from scipy.spatial.transform import Rotation as Rot

from ace_apriltags import python_module as apriltags


# TODO: import from library  # pylint: disable = fixme
def distort_point(x_undist, map_x, map_y):
    """Distort point.
    map_x contains distorted x-coordinates of point [x,y]
    map_y contains distorted y-coordinatse of point [x,y]
    """
    # pylint: disable = invalid-name, redefined-outer-name

    # bilinear interpolation
    u_low = int(x_undist[0])
    v_low = int(x_undist[1])

    u_alpha = x_undist[0] - u_low
    v_alpha = x_undist[1] - v_low

    w0 = (1.0 - u_alpha) * (1.0 - v_alpha)
    w1 = (u_alpha) * (1.0 - v_alpha)
    w2 = (1.0 - u_alpha) * (v_alpha)
    w3 = (u_alpha) * (v_alpha)

    x_dist = np.zeros(2)
    x_dist[0] = (
        w0 * map_x[v_low, u_low]
        + w1 * map_x[v_low, u_low + 1]
        + w2 * map_x[v_low + 1, u_low]
        + w3 * map_x[v_low + 1, u_low + 1]
    )
    x_dist[1] = (
        w0 * map_y[v_low, u_low]
        + w1 * map_y[v_low, u_low + 1]
        + w2 * map_y[v_low + 1, u_low]
        + w3 * map_y[v_low + 1, u_low + 1]
    )

    return x_dist


def calc_rotation(angle):  # pylint: disable = redefined-outer-name
    """Round angle to [-90, 0, 90, 180] degress."""
    while abs(angle) > 180:
        angle -= np.sign(angle) * 360

    if angle < -135 or angle >= 135:
        return 180

    if -135 <= angle < -45:
        return -90

    if -45 <= angle < 45:
        return 0

    if 45 <= angle < 135:
        return 90

    return "invalid"


if __name__ == "__main__":
    USAGE = """
    Examples:
     - calibration_set_origin --config <config> --serial_number <serial_number>
     - calibration_set_origin --config <config> --serial_number <serial_number> -x <x_offset> -y <y_offset> (see below)

    Examples of cases when `-x`, `-y`, and `-z` offsets are useful:
      - Applying `-z -0.01` to accomedate for the board thickness
      - Applying `-x -1.296 -y -0.693` offsets when placing the board at the table corner

          _________________
          |       |       |
          |       |       |
          |*______|_______|
      y
      '--->x
    """

    # setup argument list
    parser = argparse.ArgumentParser(description="Set origin of calibration.", usage=USAGE)

    parser.add_argument(
        "--config", type=str, required=True, help="Lab specific configuration, e.g. zrh00, zrh01, tyo02."
    )
    parser.add_argument(
        "--serial_number", type=str, required=True, help="Serial number of camera to be used for setting origin."
    )
    parser.add_argument(
        "--tag_cols",
        type=int,
        default=6,
        help="Number of columns in AprilTag's grid (default: %(default)s)",
    )
    parser.add_argument(
        "--tag_rows",
        type=int,
        default=6,
        help="Number of rows in AprilTag's grid (default: %(default)s)",
    )
    parser.add_argument(
        "--tag_size",
        type=float,
        default=0.088,
        help="Size of each AprilTag [in meters] (default: %(default)s)",
    )
    parser.add_argument(
        "--tag_spacing",
        type=float,
        default=0.3,
        help="Spacing between AprilTags [relative to tag_size] (default: %(default)s)",
    )
    parser.add_argument(
        "--offset",
        "-o",
        type=float,
        default=[0.0, 0.0, 0.0],
        nargs=3,
        help="3D space offset of calibration board in [m] (default: %(default)s).",
    )
    parser.add_argument(
        "--x_offset",
        "-x",
        type=float,
        default=0.0,
        help="Offset of calibration board along x-direction in [m] (default: %(default)s).",
    )
    parser.add_argument(
        "--y_offset",
        "-y",
        type=float,
        default=0.0,
        help="Offset of calibration board along y-direction in [m] (default: %(default)s).",
    )
    parser.add_argument(
        "--z_offset",
        "-z",
        type=float,
        default=0.0,
        help="Offset of calibration board along z-direction in [m] (default: %(default)s).",
    )

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    # parse argument list
    try:
        parsed = parser.parse_args()
    except Exception:  # pylint: disable = broad-except
        sys.exit(0)

    # Prepare the offset
    parsed.offset = np.array(parsed.offset)
    parsed.offset += [parsed.x_offset, parsed.y_offset, parsed.z_offset]

    # load camera calibration
    try:
        # read yaml file for storage
        FILE_PATH = "src/sensors/calibration/parameters/camera_calibration/" + parsed.config + ".yaml"
        FILE = open(FILE_PATH, "r")  # pylint: disable = unspecified-encoding, consider-using-with

        skip_line_counter = 0  # pylint: disable = invalid-name

        FILE_CONTENT = ""
        for line in FILE:
            if skip_line_counter > 0:
                skip_line_counter -= 1
                continue

            if line.startswith("T_WO:"):
                skip_line_counter = 4  # pylint: disable = invalid-name
                continue

            FILE_CONTENT += line

        FILE.close()

        # read yaml file
        FILE = open(FILE_PATH, "r")  # pylint: disable = unspecified-encoding, consider-using-with
        params = yaml.full_load(FILE)
        FILE.close()

        cam_id = "aps" + parsed.serial_number
        K = np.array(params[cam_id]["camera_matrix"])
        dist_model = params[cam_id]["distortion_model"]
        dist = np.array(params[cam_id]["distortion_coeffs"])
        T_CW = np.array(params[cam_id]["T_CW"])
        resolution = tuple(params[cam_id]["resolution"])
        if dist_model == "equidistant":
            map_x, map_y = cv2.fisheye.initUndistortRectifyMap(
                K, dist, np.eye(3), K, resolution, cv2.CV_32F
            )  # this maps could be stored
        elif dist_model == "radtan":
            map_x, map_y = cv2.initUndistortRectifyMap(
                K, dist, np.eye(3), K, resolution, cv2.CV_32F
            )  # this maps could be stored
        else:
            raise ValueError(f"Unexpected distortion model '{dist_model}'")

    except IOError:
        print("Failed to open file.")
        sys.exit()

    # set up april grid detector
    april_grid_detector = apriltags.AprilGridDetector(
        parsed.tag_rows, parsed.tag_cols, parsed.tag_size, parsed.tag_spacing
    )
    object_points = april_grid_detector.points()
    # Correct for aprilgrid offsets
    object_points += parsed.offset

    # read image
    zcs = aps.ZeroCopySubscriber()
    handle = zcs.add_subscription("/sensors/" + cam_id + "/image")

    # main loop
    should_exit = False  # pylint: disable = invalid-name
    while not should_exit:
        ret, frame_id, _, img_raw = zcs.get_latest_message(handle)

        if not ret:
            print("Waiting for image...")
            time.sleep(1)
            continue

        # detect april grid
        img = cv2.cvtColor(img_raw, cv2.COLOR_BayerBG2BGR)
        ret, image_points, corners_observed = april_grid_detector.detect(img)

        if ret:
            # solve PnP
            if dist_model == "equidistant":
                image_points_undist = cv2.fisheye.undistortPoints(
                    np.expand_dims(image_points, axis=1), K, dist, np.eye(3), K
                )
            elif dist_model == "radtan":
                image_points_undist = cv2.undistortPoints(np.expand_dims(image_points, axis=1), K, dist, np.eye(3), K)
            else:
                raise ValueError(f"Unexpected distortion model '{dist_model}'")
            image_points_undist = np.reshape(np.asarray(image_points_undist), (-1, 2))

            ret, rvec, tvec = cv2.solvePnP(
                object_points[corners_observed], image_points_undist[corners_observed], K, np.empty(0)
            )

            if not ret:
                zcs.release_latest_message(handle)
                print("Failed to solve PnP.")
                continue

            # draw results
            T_CO = np.eye(4, dtype=np.float64)
            T_CO[:3, :3] = Rot.from_rotvec(np.reshape(rvec, 3)).as_matrix()
            T_CO[:3, 3] = np.reshape(tvec, 3)

            O_op = np.transpose(object_points)
            O_op = np.vstack([O_op, np.ones((1, O_op.shape[1]))])
            C_op = T_CO.dot(O_op)

            # projection
            ip_fitted = K.dot(C_op[:3, :])
            for i in range(ip_fitted.shape[1]):
                ip_fitted[:, i] /= ip_fitted[2, i]

                if ip_fitted[0, i] < 0 or ip_fitted[0, i] > 1439:
                    continue

                if ip_fitted[1, i] < 0 or ip_fitted[1, i] > 1079:
                    continue

                # distort point
                ip_fitted[:2, i] = distort_point(ip_fitted[:2, i], map_x, map_y)

                # draw point
                ip = np.array(ip_fitted[:2, i], dtype=int)
                if corners_observed[i]:
                    cv2.circle(img, ip, 4, [255, 0, 0])
                else:
                    cv2.circle(img, ip, 4, [0, 255, 0])

            cv2.imshow("Set Origin - Camera Image", img)
            if cv2.waitKey(1) == ord("q"):
                should_exit = True  # pylint: disable = invalid-name
                zcs.release_latest_message(handle)

            zcs.release_latest_message(handle)

    # append results to file
    # T_WO = T_WC * T_CO
    T_WO = np.matmul(np.linalg.inv(T_CW), (T_CO))

    FILE_CONTENT += "T_WO:\n"
    for i in range(4):
        FILE_CONTENT += "  - [{:.17f}, {:.17f}, {:.17f}, {:.17f}]\n".format(
            T_WO[i, 0], T_WO[i, 1], T_WO[i, 2], T_WO[i, 3]
        )

    FILE = open(FILE_PATH, "w")  # pylint: disable = unspecified-encoding, consider-using-with
    FILE.write(FILE_CONTENT)
    FILE.close()

    # set orientation of camera
    params = yaml.safe_load(open(FILE_PATH, "r"))  # pylint: disable = unspecified-encoding, consider-using-with
    cam_names = [cam for cam in params.keys() if cam != "T_WO"]
    T_CWs = np.array([params[cam]["T_CW"] for cam in cam_names])
    T_WO = np.array(params["T_WO"])
    T_COs = np.array([np.matmul(T_CW, T_WO) for T_CW in T_CWs])
    T_OCs = np.array([np.linalg.inv(T_CO) for T_CO in T_COs])

    for cam, T_CO in zip(cam_names, T_COs):
        O_ez_O = np.array([0.0, 0.0, 1.0])
        C_ez_O = np.dot(T_CO[:3, :3], O_ez_O)
        C_ez_C = np.array([0.0, 0.0, 1.0])
        C_ez_O_proj = C_ez_O - np.dot(C_ez_O, C_ez_C) * C_ez_C
        C_ez_O_proj = C_ez_O_proj / np.linalg.norm(C_ez_O_proj)
        angle = np.arctan2(C_ez_O_proj[1], C_ez_O_proj[0]) / np.pi * 180 + 90
        angle = calc_rotation(angle)
        params[cam]["rotation"] = angle

    with open(FILE_PATH, "w") as yaml_file:  # pylint: disable = unspecified-encoding
        yaml_file.write(yaml.dump(params, default_flow_style=None, sort_keys=False))

    cv2.destroyAllWindows()
    sys.exit(0)
