<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ace_monitor</name>
  <version>1.0.0</version>
  <description>Standalone ImGui/ImPlot/OpenGL ROS 2 monitor.</description>
  <maintainer email="yamen.saraiji@sony.com">Yamen Saraiji</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>builtin_interfaces</depend>

  <depend>libglfw3-dev</depend>
  <depend>libglew-dev</depend>
  <depend>libglm-dev</depend>
  <depend>libstb-dev</depend>
  <depend>libfreetype-dev</depend>
  <depend>libassimp-dev</depend>
  <depend>libopencv-dev</depend>
  <depend>eigen</depend>

  <depend >ace_setuptools</depend>
  <depend >ace_loggers</depend>
  <depend >ace_yaml</depend>
  <depend >ace_interfaces</depend>
  <depend >base_parameters</depend>
  <depend >calibration</depend>
  <depend >vision_common</depend>
  <depend>pybind11_vendor</depend>
  <depend >ace_rt_profiles</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
