###################
#    SCOREBOARD   #
###################
# RT profiles used during games in the scoreboard PC

arena_native_ros:
  affinity: [3,4]

perception_default_ros:
  affinity: [5,6]

trajectory_estimator:
  affinity: [7]
