<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cuda_common</name>
  <version>0.0.30</version>
  <description>Package contains cuda related tools</description>
  <maintainer email="yamen.saraiji@sony.com">SonyAI-Tokyo</maintainer>
  <license>Confidential, Copyright 2025, Sony AI, All rights reserved.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend >ace_setuptools</depend>
  <depend >ace_loggers</depend>
  <depend>pybind11_vendor</depend>
  <depend>vision_common</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
