<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ball_detector</name>
  <version>1.0.42</version>
  <description>Package to detect 2D ball points from image observations containing a ball or more</description>
  <maintainer email="hamdi.sahloul@sony.com">SonyAI-Tokyo</maintainer>
  <license>Confidential, Copyright 2025, Sony AI, All rights reserved.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend >ace_setuptools</depend>
  <depend >ace_loggers</depend>
  <depend>pybind11_vendor</depend>
  <depend >rosbag_dataloaders</depend>

  <!-- TODO transitive dependency from ace_loggers -->
  <depend>ace_rt_profiles</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
