
model_engine_path: /mnt/tokyo_nas/shared_nas/models/ball_detector/zero_copy/model.onnx

sampling: 1
batch_size: 1
device_ids: [] # TODO: add device ids when we have multiple GPUs

minimum_confidence: 0.3

camera_names: []

rt_profile: ball_detection_trt
