defaults:
  - defaults.yaml
  
batch_size: 3
device_ids: 
  - 0
  - 1
sampling: 2
minimum_confidence: 0.4

camera_names: 
  - aps23175185
  - aps23175188
  - aps23175575
  - aps23175992
  - aps22240289
  - aps22240293
