acquisition_control:
  acquisition_mode: 0
  exposure_mode: 0
  exposure_auto: 0
  acquisition_frame_rate: 200.0
  acquisition_frame_rate_enable: true
analog_control:
  gain_auto: 0
  black_level: 0
  black_level_clamping_enable: true
  balance_white_auto: 0
  gamma_enable: true
image_format_control:
  width: 1440
  height: 1080
  offset_x: 0
  offset_y: 0
  pixel_format: 4
  adc_bit_depth: 1
chunk_data_control:
  chunk_mode_active: false
  exposure_time: false
  timestamp: false
stream_buffer_control:
  manual_stream_buffer_count: 50
  stream_buffer_count_mode: 0
  stream_buffer_handling_mode: 0
