<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ace_rt_profiles</name>
  <version>2.0.4</version>
  <description>A centralized place for controlling real time profiles</description>
  <maintainer email="tiago.silva@sony.com">Tiago Silva</maintainer>
  <license>Confidential, Copyright 2025, Sony AI, All rights reserved</license>

  <buildtool_depend>ament_cmake_python</buildtool_depend>


  <depend>ace_setuptools</depend>
  <depend>ament_index_cpp</depend>
  <depend >ace_yaml</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
