<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>racket_pose_estimation</name>
  <version>0.0.58</version>
  <description>Racket Pose Estimation</description>
  <maintainer email="yamen.saraiji@sony.com">SonyAI-Tokyo</maintainer>
  <license>Confidential, Copyright 2026, Sony AI, All rights reserved.</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>ace_setuptools</depend>
  <depend >ace_loggers</depend>
  <depend >rosbag_dataloaders</depend>
  <depend>ace_yaml</depend>
  <depend>ace_interfaces</depend>
  <depend>aps</depend>
  <depend>calibration</depend>
  <depend>triangulation</depend>
  <depend>vision_common</depend>
  <depend>cuda_common</depend>
  <depend>base_parameters</depend>
  <depend>python_helpers</depend>
  <depend>state_estimation</depend>
  <depend>rclcpp</depend>
  <depend >ace_rt_profiles</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
