<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aps</name>
  <version>1.0.101</version>
  <description>APS camera package to run one or multiple APS cameras.</description>
  <maintainer email="dario.brescianini@sony.com">SonyAI-Zurich</maintainer>
  <license>Confidential, Copyright 2025, Sony AI, All rights reserved.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend >ace_loggers</depend>
  <depend >ace_yaml</depend>
  <depend >ace_interfaces</depend>
  <depend>cuda_common</depend>
  <depend >vision_common</depend>
  <depend >base_parameters</depend>
  <depend>pybind11_vendor</depend>
  <depend>rclcpp</depend>
  <depend>calibration</depend>
  <depend>ace_rt_profiles</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
